task:
  name: "Kernel Build"
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 4
      memory: 16G

  Build_script:
      - git clone --depth=1 https://github.com/Subash2001/RMX1821.git kernel && cd kernel
      - bash build.sh
